### ISSUE TITLE
Android - Crashes if launched without SIM Card 

### ISSUE THREAD

**Issue by alisafni** [SaferMobile/InTheClear#90]
Android, Nexus S, 2.3.6.
If you launch InTheClear without a SIM Card inserted, "The application InTheClear (process org.safermobile.intheclear) has stopped unexpectedly.".

**Comment by alisafni** [comment]
Stacktrace of Crash w/o SIM:

I/ActivityManager(  146): Start proc org.safermobile.intheclear for activity org.safermobile.intheclear/.apps.Panic: pid=5133 uid=10066 gids={1015}
I/dalvikvm( 5133): Turning on JNI app bug workarounds for target SDK version 8...
D/AndroidRuntime( 5133): Shutting down VM
W/dalvikvm( 5133): threadid=1: thread exiting with uncaught exception (group=0x40a351f8)
E/AndroidRuntime( 5133): FATAL EXCEPTION: main
E/AndroidRuntime( 5133): java.lang.RuntimeException: Unable to create service org.safermobile.intheclear.controllers.PanicController: java.lang.NullPointerException
E/AndroidRuntime( 5133):    at android.app.ActivityThread.handleCreateService(ActivityThread.java:2263)
E/AndroidRuntime( 5133):    at android.app.ActivityThread.access$1600(ActivityThread.java:123)
E/AndroidRuntime( 5133):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1201)
E/AndroidRuntime( 5133):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 5133):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 5133):    at android.app.ActivityThread.main(ActivityThread.java:4424)
E/AndroidRuntime( 5133):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 5133):    at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 5133):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
E/AndroidRuntime( 5133):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
E/AndroidRuntime( 5133):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 5133): Caused by: java.lang.NullPointerException
E/AndroidRuntime( 5133):    at org.safermobile.intheclear.controllers.ShoutController.buildShoutData(ShoutController.java:54)
E/AndroidRuntime( 5133):    at org.safermobile.intheclear.controllers.PanicController.alignPreferences(PanicController.java:73)
E/AndroidRuntime( 5133):    at org.safermobile.intheclear.controllers.PanicController.onCreate(PanicController.java:62)
E/AndroidRuntime( 5133):    at android.app.ActivityThread.handleCreateService(ActivityThread.java:2253)
E/AndroidRuntime( 5133):    ... 10 more
W/ActivityManager(  146):   Force finishing activity org.safermobile.intheclear/.apps.Panic
